In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv

In [2]:
us_file="us_postal_codes.csv"
us_data=pd.read_csv(us_file)
us_data=us_data.rename(columns={"Zip Code":"Zipcode"})
us_data.dtypes

Zipcode                 int64
Place Name             object
State                  object
State Abbreviation     object
County                 object
Latitude              float64
Longitude             float64
dtype: object

In [3]:
economic_data_2015= "Census_2015/census_economic_2015.csv"
census_eco_2015= pd.read_csv(economic_data_2015)
census_eco_2015.dtypes

Zipcode                 int64
Population            float64
Median Age            float64
Household Income      float64
Per Capita Income     float64
Poverty Count         float64
Poverty Rate          float64
Employable Count      float64
Unemployment Count    float64
Unemployment Rate     float64
dtype: object

In [4]:
census_eco_2015.count()

Zipcode               33120
Population            33120
Median Age            32615
Household Income      31067
Per Capita Income     32542
Poverty Count         33120
Poverty Rate          32810
Employable Count      33120
Unemployment Count    33120
Unemployment Rate     32597
dtype: int64

In [5]:
combined_eco_2015=pd.merge(us_data, census_eco_2015, on="Zipcode")
combined_eco_2015.head()
combined_eco_2015.to_csv("Census_2015/combined_eco_2015.csv")

In [6]:
combined_eco_2015.count()

Zipcode               32972
Place Name            32972
State                 32972
State Abbreviation    32972
County                32972
Latitude              32972
Longitude             32972
Population            32972
Median Age            32475
Household Income      30932
Per Capita Income     32403
Poverty Count         32972
Poverty Rate          32669
Employable Count      32972
Unemployment Count    32972
Unemployment Rate     32460
dtype: int64

In [7]:
grouped_eco_2015= combined_eco_2015.groupby(["County"])
grouped_eco_2015.count()

,Zipcode,Place Name,State,State Abbreviation,Latitude,Longitude,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Employable Count,Unemployment Count,Unemployment Rate
County,,,,,,,,,,,,,,,
Abbeville,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Acadia,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Accomack,33,33,33,33,33,33,33,33,22,33,33,33,33,33,33
Ada,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Adair,19,19,19,19,19,19,19,19,17,19,19,19,19,19,19
Adams,88,88,88,88,88,88,88,87,85,87,88,87,88,88,87
Addison,17,17,17,17,17,17,17,16,16,16,17,16,17,17,16
Aiken,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Aitkin,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Alachua,20,20,20,20,20,20,20,20,19,20,20,20,20,20,20
Alamance,9,9,9,9,9,9,9,8,8,8,9,9,9,9,9
Alameda,49,49,49,49,49,49,49,49,47,49,49,49,49,49,49
Alamosa,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Albany,46,46,46,46,46,46,46,43,38,43,46,45,46,46,43
Albemarle,13,13,13,13,13,13,13,13,11,13,13,13,13,13,13
Alcona,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Alcorn,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Aleutians East,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Aleutians West (CA),7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Alexander,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Alfalfa,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Alger,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Allamakee,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Allegan,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Allegany,40,40,40,40,40,40,40,40,39,40,40,40,40,40,40
Alleghany,9,9,9,9,9,9,9,9,8,9,9,9,9,9,9
Allegheny,101,101,101,101,101,101,101,99,96,99,101,99,101,101,99
Allen,56,56,56,56,56,56,56,56,53,56,56,56,56,56,56
Allendale,4,4,4,4,4,4,4,4,3,4,4,4,4,4,4
Alpena,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Worcester,97,97,97,97,97,97,97,97,96,97,97,97,97,97,97
Worth,17,17,17,17,17,17,17,17,16,17,17,17,17,17,17
Wrangell-Petersburg (C,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Wright,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
Wyandot,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Wyandotte,12,12,12,12,12,12,12,10,10,10,12,10,12,12,10
Wyoming,61,61,61,61,61,61,61,61,53,61,61,61,61,61,59
Wythe,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Yadkin,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Yakima,21,21,21,21,21,21,21,21,20,21,21,21,21,21,21
Yalobusha,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Yamhill,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yancey,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Yankton,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Yates,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yavapai,26,26,26,26,26,26,26,26,25,26,26,26,26,26,26
Yazoo,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Yell,10,10,10,10,10,10,10,10,7,10,10,10,10,10,10
Yellow Medicine,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Yellowstone,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Yoakum,3,3,3,3,3,3,3,3,2,3,3,3,3,3,3
Yolo,18,18,18,18,18,18,18,17,16,17,18,18,18,18,18
York,99,99,99,99,99,99,99,99,95,99,99,99,99,99,99
Young,5,5,5,5,5,5,5,5,4,5,5,5,5,5,5
Yuba,11,11,11,11,11,11,11,10,10,10,11,11,11,11,11
Yukon-Koyukuk (CA),29,29,29,29,29,29,29,29,27,29,29,29,29,29,29
Yuma,17,17,17,17,17,17,17,17,15,17,17,17,17,17,17
Zapata,3,3,3,3,3,3,3,2,2,2,3,3,3,3,3
Zavala,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Ziebach,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2

In [8]:
population_sum=grouped_eco_2015["Population"].sum().tolist()
household_income_sum=grouped_eco_2015["Household Income"].sum().tolist()
per_capita_sum=grouped_eco_2015["Per Capita Income"].sum().tolist()
poverty_sum=grouped_eco_2015["Poverty Count"].sum().tolist()
employable_count=grouped_eco_2015["Employable Count"].sum().tolist()
unemployable_count=grouped_eco_2015["Unemployment Count"].sum().tolist()

In [9]:
county_eco_list=[]
for x, group in grouped_eco_2015:
    county_eco_list.append(x)
    
print(len(county_eco_list))

1850

In [10]:
eco_2015_df=pd.DataFrame(county_eco_list, columns=["County"])
eco_2015_df["Population"]= population_sum
eco_2015_df["Household Income"]= household_income_sum
eco_2015_df["Per Capita Income"]= per_capita_sum
eco_2015_df["Poverty Count"]= poverty_sum
eco_2015_df["Poverty Rate"] = 100 * \
    eco_2015_df["Poverty Count"].astype(
        int) / eco_2015_df["Population"].astype(int)

eco_2015_df["Employable Count"]=employable_count
eco_2015_df["Unemployment Count"]=unemployable_count
eco_2015_df["Unemployment Rate"] = 100 * \
    eco_2015_df["Unemployment Count"].astype(
        int) / eco_2015_df["Employable Count"].astype(int)

In [11]:
eco_2015_df

,County,Population,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Employable Count,Unemployment Count,Unemployment Rate
0,Abbeville,20388.0,166746.0,77384.0,4875.0,23.911124,8544.0,1013.0,11.856273
1,Acadia,60580.0,425943.0,220309.0,12655.0,20.889733,25994.0,2503.0,9.629145
2,Accomack,33115.0,904956.0,701817.0,6384.0,19.278273,15335.0,1039.0,6.775351
3,Ada,366618.0,811864.0,427588.0,46423.0,12.662499,190479.0,12825.0,6.733026
4,Adair,72517.0,668627.0,386361.0,16133.0,22.247197,32694.0,2430.0,7.432556
5,Adams,822409.0,4451991.0,2120933.0,116308.0,14.142355,418794.0,31983.0,7.636929
6,Addison,36358.0,941803.0,464511.0,3108.0,8.548325,20392.0,1140.0,5.590428
7,Aiken,165345.0,680344.0,357852.0,28838.0,17.441108,77525.0,7588.0,9.787810
8,Aitkin,16055.0,336984.0,194688.0,1949.0,12.139520,7184.0,541.0,7.530624
9,Alachua,266511.0,853164.0,473456.0,59892.0,22.472618,131868.0,10480.0,7.947341
10,Alamance,162092.0,388783.0,205041.0,29166.0,17.993485,80787.0,6200.0,7.674502
11,Alameda,1590894.0,3809725.0,1932466.0,195047.0,12.260213,851490.0,70218.0,8.246486
12,Alamosa,16287.0,107659.0,62041.0,4388.0,26.941733,7039.0,732.0,10.399204
13,Albany,325691.0,2388422.0,1318562.0,48346.0,14.844131,176246.0,10997.0,6.239574
14,Albemarle,81608.0,737645.0,470322.0,7554.0,9.256445,41516.0,1449.0,3.490221
15,Alcona,10139.0,351970.0,204979.0,1519.0,14.981754,3746.0,477.0,12.733582
16,Alcorn,36184.0,104088.0,56736.0,7794.0,21.539907,15946.0,1450.0,9.093190
17,Aleutians East,3304.0,282394.0,169369.0,553.0,16.737288,2593.0,74.0,2.853837
18,Aleutians West (CA),5473.0,452101.0,190821.0,499.0,9.117486,3701.0,83.0,2.242637
19,Alexander,44965.0,313294.0,144101.0,8665.0,19.270544,20913.0,2195.0,10.495864
20,Alfalfa,5924.0,426071.0,234335.0,616.0,10.398379,2347.0,118.0,5.027695
21,Alger,9323.0,402184.0,244754.0,1223.0,13.118095,3483.0,377.0,10.824002
22,Allamakee,14235.0,338943.0,200710.0,1629.0,11.443625,7423.0,460.0,6.196955
23,Allegan,98980.0,755101.0,342261.0,11467.0,11.585169,47564.0,3045.0,6.401901
24,Allegany,122917.0,1692258.0,878313.0,19286.0,15.690263,56290.0,5502.0,9.774383
25,Alleghany,17686.0,322114.0,188528.0,3545.0,20.044103,7644.0,699.0,9.144427
26,Allegheny,1219265.0,5253506.0,3118975.0,155463.0,12.750551,652272.0,46160.0,7.076802
27,Allen,515908.0,2578085.0,1300999.0,82515.0,15.994131,256449.0,21512.0,8.388413
28,Allendale,9929.0,98602.0,63391.0,2582.0,26.004633,3731.0,839.0,22.487269
29,Alpena,29221.0,202156.0,110969.0,4935.0,16.888539,13340.0,1264.0,9.475262
...,...,...,...,...,...,...,...,...,...
1820,Worcester,864547.0,7130475.0,3221038.0,98150.0,11.352766,464360.0,36693.0,7.901843
1821,Worth,26363.0,724484.0,394381.0,4582.0,17.380420,12408.0,914.0,7.366215
1822,Wrangell-Petersburg (C,6245.0,239106.0,106412.0,734.0,11.753403,3308.0,322.0,9.733978
1823,Wright,160430.0,1709736.0,797799.0,14087.0,8.780777,84785.0,4760.0,5.614201
1824,Wyandot,23911.0,392235.0,201123.0,2861.0,11.965204,12606.0,831.0,6.592099
1825,Wyandotte,164367.0,424890.0,194322.0,38078.0,23.166451,81475.0,8967.0,11.005830
1826,Wyoming,95991.0,2381007.0,1362904.0,12954.0,13.495015,42972.0,3388.0,7.884204
1827,Wythe,31215.0,346011.0,183911.0,4765.0,15.265097,14905.0,1407.0,9.439785
1828,Yadkin,38917.0,184709.0,108137.0,7939.0,20.399825,17511.0,1479.0,8.446120
1829,Yakima,248684.0,911277.0,367352.0,52336.0,21.045182,111740.0,10104.0,9.042420
1830,Yalobusha,15618.0,211831.0,101461.0,2748.0,17.595083,6979.0,500.0,7.164350
1831,Yamhill,100921.0,554623.0,252869.0,16037.0,15.890647,48727.0,4813.0,9.877481
1832,Yancey,17765.0,78190.0,40420.0,3769.0,21.215874,7970.0,869.0,10.903388
1833,Yankton,21997.0,342983.0,168283.0,2943.0,13.379097,11397.0,420.0,3.685180
1834,Yates,26837.0,569508.0,265912.0,3684.0,13.727317,13141.0,861.0,6.552013
1835,Yavapai,201147.0,1046695.0,607028.0,33030.0,16.420827,83422.0,8412.0,10.083671
1836,Yazoo,27878.0,235580.0,112409.0,7963.0,28.563742,10468.0,2070.0,19.774551
1837,Yell,22582.0,266848.0,191585.0,4113.0,18.213621,9596.0,806.0,8.399333
1838,Yellow Medicine,10734.0,386013.0,193066.0,1196.0,11.142165,5684.0,198.0,3.483462
1839,Yellowstone,153904.0,699329.0,360749.0,17187.0,11.167351,82065.0,3382.0,4.121123
1840,Yoakum,8835.0,115293.0,84577.0,998.0,11.295982,4146.0,330.0,7.959479
1841,Yolo,209126.0,894935.0,449829.0,39787.0,19.025372,102964.0,9263.0,8.996348
1842,York,940976.0,5697687.0,2853317.0,100740.0,10.705905,499288.0,36079.0,7.226090
1843,Young,19028.0,221731.0,111479.0,2859.0,15.025226,9025.0,496.0,5.495845
1844,Yuba,72603.0,499482.0,261310.0,15545.0,21.410961,29603.0,4422.0,14.937675
1845,Yukon-Koyukuk (CA),5600.0,960071.0,580097.0,1244.0,22.214286,2512.0,461.0,18.351911
1846,Yuma,213136.0,648877.0,371931.0,41896.0,19.656933,87392.0,10891.0,12.462239
1847,Zapata,14085.0,64181.0,46607.0,5129.0,36.414625,5849.0,721.0,12.326893
1848,Zavala,12077.0,71173.0,39847.0,3950.0,32.706798,4876.0,593.0,12.161608
1849,Ziebach,1397.0,59250.0,22777.0,417.0,29.849678,621.0,128.0,20.611916

In [12]:
eco_2015_df.to_csv("Census_2015/eco_2015_by_County.csv")

In [13]:
economic_data_2016= "Census_2016/census_economic_2016.csv"
census_eco_2016= pd.read_csv(economic_data_2016)
census_eco_2016.dtypes

Zipcode                 int64
Population            float64
Median Age            float64
Household Income      float64
Per Capita Income     float64
Poverty Count         float64
Poverty Rate          float64
Employable Count      float64
Unemployment Count    float64
Unemployment Rate     float64
dtype: object

In [14]:
census_eco_2016.count()

Zipcode               33120
Population            33120
Median Age            33120
Household Income      33120
Per Capita Income     32836
Poverty Count         33120
Poverty Rate          32799
Employable Count      33120
Unemployment Count    33120
Unemployment Rate     32577
dtype: int64

In [15]:
combined_eco_2016=pd.merge(us_data, census_eco_2016, on="Zipcode")
combined_eco_2016.head()
combined_eco_2016.to_csv("Census_2016/combined_eco_2016.csv")

In [16]:
combined_eco_2016.count()

Zipcode               32972
Place Name            32972
State                 32972
State Abbreviation    32972
County                32972
Latitude              32972
Longitude             32972
Population            32972
Median Age            32972
Household Income      32972
Per Capita Income     32691
Poverty Count         32972
Poverty Rate          32658
Employable Count      32972
Unemployment Count    32972
Unemployment Rate     32441
dtype: int64

In [17]:
grouped_eco_2016= combined_eco_2016.groupby(["County"])
grouped_eco_2016.count()

,Zipcode,Place Name,State,State Abbreviation,Latitude,Longitude,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Employable Count,Unemployment Count,Unemployment Rate
County,,,,,,,,,,,,,,,
Abbeville,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Acadia,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Accomack,33,33,33,33,33,33,33,33,33,32,33,33,33,33,33
Ada,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Adair,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
Adams,88,88,88,88,88,88,88,88,88,88,88,87,88,88,87
Addison,17,17,17,17,17,17,17,17,17,17,17,16,17,17,16
Aiken,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Aitkin,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Alachua,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
Alamance,9,9,9,9,9,9,9,9,9,8,9,9,9,9,9
Alameda,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49
Alamosa,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Albany,46,46,46,46,46,46,46,46,46,45,46,44,46,46,43
Albemarle,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Alcona,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Alcorn,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Aleutians East,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Aleutians West (CA),7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Alexander,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Alfalfa,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Alger,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Allamakee,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Allegan,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Allegany,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40
Alleghany,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Allegheny,101,101,101,101,101,101,101,101,101,101,101,99,101,101,99
Allen,56,56,56,56,56,56,56,56,56,55,56,56,56,56,56
Allendale,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Alpena,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Worcester,97,97,97,97,97,97,97,97,97,97,97,97,97,97,97
Worth,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Wrangell-Petersburg (C,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Wright,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
Wyandot,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Wyandotte,12,12,12,12,12,12,12,12,12,12,12,10,12,12,10
Wyoming,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61
Wythe,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Yadkin,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Yakima,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21
Yalobusha,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Yamhill,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yancey,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Yankton,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Yates,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yavapai,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26
Yazoo,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Yell,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yellow Medicine,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Yellowstone,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Yoakum,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Yolo,18,18,18,18,18,18,18,18,18,17,18,18,18,18,17
York,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
Young,5,5,5,5,5,5,5,5,5,4,5,5,5,5,5
Yuba,11,11,11,11,11,11,11,11,11,10,11,11,11,11,11
Yukon-Koyukuk (CA),29,29,29,29,29,29,29,29,29,29,29,29,29,29,29
Yuma,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Zapata,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Zavala,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Ziebach,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2

In [18]:
population_sum=grouped_eco_2016["Population"].sum().tolist()
household_income_sum=grouped_eco_2016["Household Income"].sum().tolist()
per_capita_sum=grouped_eco_2016["Per Capita Income"].sum().tolist()
poverty_sum=grouped_eco_2016["Poverty Count"].sum().tolist()
employable_count=grouped_eco_2016["Employable Count"].sum().tolist()
unemployable_count=grouped_eco_2016["Unemployment Count"].sum().tolist()

In [19]:
county_eco_2016=[]
for x, group in grouped_eco_2016:
    county_eco_2016.append(x)
    
print(len(county_eco_2016))

1850

In [20]:
eco_2016_df=pd.DataFrame(county_eco_2016, columns=["County"])
eco_2016_df["Population"]= population_sum
eco_2016_df["Household Income"]= household_income_sum
eco_2016_df["Per Capita Income"]= per_capita_sum
eco_2016_df["Poverty Count"]= poverty_sum
eco_2016_df["Poverty Rate"] = 100 * \
    eco_2016_df["Poverty Count"].astype(
        int) / eco_2016_df["Population"].astype(int)

eco_2016_df["Employable Count"]=employable_count
eco_2016_df["Unemployment Count"]=unemployable_count
eco_2016_df["Unemployment Rate"] = 100 * \
    eco_2016_df["Unemployment Count"].astype(
        int) / eco_2016_df["Employable Count"].astype(int)

In [21]:
eco_2016_df

,County,Population,Household Income,Per Capita Income,Poverty Count,Poverty Rate,Employable Count,Unemployment Count,Unemployment Rate
0,Abbeville,20747.0,1.756290e+05,8.328500e+04,4669.0,22.504458,8877.0,780.0,8.786752
1,Acadia,61112.0,-1.333005e+09,2.223470e+05,12667.0,20.727517,26488.0,2331.0,8.800211
2,Accomack,33060.0,-7.999144e+09,6.959200e+05,6341.0,19.180278,15206.0,1069.0,7.030120
3,Ada,373433.0,8.304840e+05,4.461840e+05,46806.0,12.533975,194615.0,10677.0,5.486216
4,Adair,72700.0,-6.659474e+08,3.960530e+05,17031.0,23.426410,32271.0,1892.0,5.862849
5,Adams,831891.0,-2.662156e+09,-6.644819e+08,113485.0,13.641811,422713.0,26306.0,6.223135
6,Addison,36344.0,-6.657089e+08,-6.661817e+08,2949.0,8.114132,20351.0,979.0,4.810574
7,Aiken,166495.0,-6.660204e+08,3.742210e+05,28139.0,16.900808,78130.0,7820.0,10.008959
8,Aitkin,15914.0,3.572170e+05,2.058950e+05,1972.0,12.391605,6972.0,484.0,6.942054
9,Alachua,268516.0,-6.657808e+08,4.848870e+05,60292.0,22.453783,131757.0,9390.0,7.126756
10,Alamance,163481.0,-6.662640e+08,1.928230e+05,28312.0,17.318220,81987.0,5444.0,6.640077
11,Alameda,1611207.0,-1.329326e+09,2.024276e+06,189954.0,11.789547,865661.0,61451.0,7.098737
12,Alamosa,16398.0,1.064870e+05,5.974000e+04,4802.0,29.284059,6994.0,605.0,8.650272
13,Albany,326664.0,-5.331078e+09,-1.331986e+09,46321.0,14.180014,177327.0,10251.0,5.780846
14,Albemarle,82037.0,8.804660e+05,4.680630e+05,7101.0,8.655850,42482.0,1281.0,3.015395
15,Alcona,10061.0,3.512210e+05,2.054950e+05,1451.0,14.422026,3693.0,397.0,10.750068
16,Alcorn,36420.0,1.165990e+05,5.913200e+04,7282.0,19.994509,16069.0,1259.0,7.834962
17,Aleutians East,3299.0,2.851640e+05,1.701660e+05,510.0,15.459230,2532.0,66.0,2.606635
18,Aleutians West (CA),5512.0,4.616070e+05,2.032490e+05,426.0,7.728592,3966.0,45.0,1.134644
19,Alexander,44113.0,-6.663849e+08,1.480040e+05,8127.0,18.423141,19722.0,1670.0,8.467701
20,Alfalfa,5993.0,4.688780e+05,2.425250e+05,614.0,10.245286,2400.0,103.0,4.291667
21,Alger,9149.0,4.116390e+05,2.392950e+05,1107.0,12.099683,3377.0,270.0,7.995262
22,Allamakee,14218.0,3.491810e+05,2.064800e+05,1604.0,11.281474,7373.0,352.0,4.774176
23,Allegan,100018.0,7.810520e+05,3.513370e+05,10682.0,10.680078,48285.0,2418.0,5.007766
24,Allegany,121890.0,-6.649049e+08,8.977750e+05,18795.0,15.419641,55208.0,4924.0,8.918997
25,Alleghany,17499.0,3.552110e+05,1.940740e+05,3677.0,21.012629,7479.0,482.0,6.444712
26,Allegheny,1218281.0,-2.661250e+09,-1.330117e+09,152075.0,12.482752,654519.0,42158.0,6.441066
27,Allen,518817.0,-2.664073e+09,1.334400e+06,78543.0,15.138864,258331.0,18593.0,7.197355
28,Allendale,9614.0,-6.665675e+08,6.309700e+04,2519.0,26.201373,3379.0,597.0,17.667949
29,Alpena,29065.0,2.059670e+05,1.100810e+05,4701.0,16.174093,13364.0,1067.0,7.984136
...,...,...,...,...,...,...,...,...,...
1820,Worcester,867019.0,-1.992814e+09,3.323854e+06,95381.0,11.001028,466816.0,31678.0,6.785971
1821,Worth,26556.0,8.258580e+05,4.053980e+05,3970.0,14.949541,12713.0,877.0,6.898450
1822,Wrangell-Petersburg (C,6267.0,2.251420e+05,1.076240e+05,643.0,10.260093,3249.0,256.0,7.879347
1823,Wright,161036.0,1.751049e+06,8.228470e+05,13599.0,8.444696,85460.0,4256.0,4.980108
1824,Wyandot,24066.0,3.880030e+05,2.038620e+05,2610.0,10.845176,12494.0,674.0,5.394589
1825,Wyandotte,165428.0,-1.332893e+09,-1.333132e+09,36523.0,22.077883,81889.0,7542.0,9.210028
1826,Wyoming,94971.0,-7.331071e+09,1.428599e+06,11962.0,12.595424,42710.0,3397.0,7.953641
1827,Wythe,30900.0,-6.663533e+08,2.021710e+05,4893.0,15.834951,14517.0,1083.0,7.460219
1828,Yadkin,38985.0,1.884100e+05,1.097230e+05,7441.0,19.086828,17168.0,1186.0,6.908201
1829,Yakima,249145.0,-6.657159e+08,3.844690e+05,50849.0,20.409400,112604.0,9464.0,8.404675
1830,Yalobusha,16095.0,2.087760e+05,9.460600e+04,3017.0,18.744952,7051.0,497.0,7.048646
1831,Yamhill,102390.0,5.773410e+05,2.614050e+05,15440.0,15.079598,48675.0,4063.0,8.347201
1832,Yancey,17770.0,6.952200e+04,4.164300e+04,3703.0,20.838492,7707.0,721.0,9.355132
1833,Yankton,21947.0,3.669830e+05,1.801460e+05,3055.0,13.919898,11536.0,340.0,2.947295
1834,Yates,26983.0,-6.661426e+08,2.618530e+05,3641.0,13.493681,13136.0,927.0,7.056943
1835,Yavapai,203845.0,-1.332287e+09,6.409960e+05,30538.0,14.980990,83942.0,7378.0,8.789402
1836,Yazoo,27691.0,1.960790e+05,1.074080e+05,8110.0,29.287494,9998.0,1786.0,17.863573
1837,Yell,22496.0,-6.663585e+08,2.029960e+05,3828.0,17.016358,9730.0,680.0,6.988695
1838,Yellow Medicine,10702.0,3.953500e+05,1.983780e+05,1142.0,10.670903,5602.0,179.0,3.195287
1839,Yellowstone,155540.0,-6.659846e+08,3.763970e+05,15647.0,10.059792,82715.0,3111.0,3.761107
1840,Yoakum,9061.0,-6.665506e+08,8.769300e+04,1008.0,11.124600,4306.0,379.0,8.801672
1841,Yolo,211422.0,-1.332386e+09,4.691880e+05,39024.0,18.457871,102810.0,8152.0,7.929190
1842,York,947713.0,-1.327407e+09,2.928596e+06,97189.0,10.255109,500655.0,31683.0,6.328310
1843,Young,19096.0,-6.664480e+08,1.048980e+05,2849.0,14.919355,9247.0,364.0,3.936412
1844,Yuba,73015.0,-1.332898e+09,2.617620e+05,14780.0,20.242416,29876.0,3819.0,12.782836
1845,Yukon-Koyukuk (CA),5536.0,-1.999072e+09,5.672160e+05,1289.0,23.283960,2502.0,470.0,18.784972
1846,Yuma,213411.0,-6.659833e+08,3.789540e+05,41737.0,19.557099,88186.0,10477.0,11.880571
1847,Zapata,13956.0,-6.665854e+08,5.685600e+04,4629.0,33.168530,5807.0,711.0,12.243844
1848,Zavala,12149.0,-6.666105e+08,3.952900e+04,4255.0,35.023459,4824.0,576.0,11.940299
1849,Ziebach,1409.0,5.975500e+04,2.490300e+04,470.0,33.356991,673.0,156.0,23.179792

In [23]:
eco_2016_df.to_csv("Census_2016/eco_2016_by_County.csv")