In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv

In [2]:
us_file="us_postal_codes.csv"
us_data=pd.read_csv(us_file)
us_data=us_data.rename(columns={"Zip Code":"Zipcode"})
us_data.dtypes

Zipcode                 int64
Place Name             object
State                  object
State Abbreviation     object
County                 object
Latitude              float64
Longitude             float64
dtype: object

In [3]:
education_data_2015= "Census_2015/census_education_2015.csv"
census_edu_2015= pd.read_csv(education_data_2015)
census_edu_2015.dtypes

Zipcode                  int64
Population             float64
None                   float64
High School Degree     float64
GED                    float64
Associate Degree       float64
Bachelor Degree        float64
Masters Degree         float64
Professional Degree    float64
Doctorate Degree       float64
dtype: object

In [4]:
census_edu_2015.count()

Zipcode                33120
Population             33120
None                   33120
High School Degree     33120
GED                    33120
Associate Degree       33120
Bachelor Degree        33120
Masters Degree         33120
Professional Degree    33120
Doctorate Degree       33120
dtype: int64

In [5]:
combined_edu_2015=pd.merge(us_data, census_edu_2015, on="Zipcode")
combined_edu_2015.head()
combined_edu_2015.to_csv("Census_2015/combined_edu_2015.csv")

In [6]:
combined_edu_2015.count()

Zipcode                32972
Place Name             32972
State                  32972
State Abbreviation     32972
County                 32972
Latitude               32972
Longitude              32972
Population             32972
None                   32972
High School Degree     32972
GED                    32972
Associate Degree       32972
Bachelor Degree        32972
Masters Degree         32972
Professional Degree    32972
Doctorate Degree       32972
dtype: int64

In [7]:
grouped_edu_2015= combined_edu_2015.groupby(["County"])
grouped_edu_2015.count()

,Zipcode,Place Name,State,State Abbreviation,Latitude,Longitude,Population,None,High School Degree,GED,Associate Degree,Bachelor Degree,Masters Degree,Professional Degree,Doctorate Degree
County,,,,,,,,,,,,,,,
Abbeville,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Acadia,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Accomack,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33
Ada,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Adair,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
Adams,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88
Addison,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Aiken,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Aitkin,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Alachua,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
Alamance,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Alameda,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49
Alamosa,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Albany,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46
Albemarle,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Alcona,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Alcorn,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Aleutians East,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Aleutians West (CA),7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Alexander,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Alfalfa,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Alger,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Allamakee,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Allegan,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Allegany,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40
Alleghany,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Allegheny,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101
Allen,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56
Allendale,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Alpena,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Worcester,97,97,97,97,97,97,97,97,97,97,97,97,97,97,97
Worth,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Wrangell-Petersburg (C,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Wright,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
Wyandot,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Wyandotte,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Wyoming,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61
Wythe,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Yadkin,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Yakima,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21
Yalobusha,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Yamhill,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yancey,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Yankton,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Yates,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yavapai,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26
Yazoo,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Yell,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yellow Medicine,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Yellowstone,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Yoakum,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Yolo,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18
York,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
Young,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Yuba,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
Yukon-Koyukuk (CA),29,29,29,29,29,29,29,29,29,29,29,29,29,29,29
Yuma,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Zapata,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Zavala,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Ziebach,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2

In [8]:
population_sum=grouped_edu_2015["Population"].sum().tolist()
none_sum=grouped_edu_2015["None"].sum().tolist()
ged_sum=grouped_edu_2015["GED"].sum().tolist()
high_school_sum=grouped_edu_2015["High School Degree"].sum().tolist()
associate_sum=grouped_edu_2015["Associate Degree"].sum().tolist()
bachelor_sum=grouped_edu_2015["Bachelor Degree"].sum().tolist()
masters_sum=grouped_edu_2015["Masters Degree"].sum().tolist()
doctorate_sum=grouped_edu_2015["Doctorate Degree"].sum().tolist()
professional_sum=grouped_edu_2015["Professional Degree"].sum().tolist()

In [9]:
county_edu_list=[]
state_list=[]
for x, group in grouped_edu_2015:
    county_edu_list.append(x)
        
    
print(len(county_edu_list))

1850

In [10]:
edu_2015_df=pd.DataFrame(county_edu_list, columns=["County"])
edu_2015_df["Population"]= population_sum
edu_2015_df["None"]= none_sum
edu_2015_df["GED"]= ged_sum
edu_2015_df["High School Degree"]= high_school_sum
edu_2015_df["Associate Degree"]= associate_sum
edu_2015_df["Bachelor Degree"]= bachelor_sum
edu_2015_df["Masters Degree"]= masters_sum
edu_2015_df["Professional Degree"]= professional_sum
edu_2015_df["Doctorate Degree"]= doctorate_sum

edu_2015_df

,County,Population,None,GED,High School Degree,Associate Degree,Bachelor Degree,Masters Degree,Professional Degree,Doctorate Degree
0,Abbeville,20388.0,127.0,800.0,4246.0,1219.0,1108.0,350.0,83.0,68.0
1,Acadia,60580.0,621.0,2260.0,12652.0,2463.0,2966.0,691.0,222.0,108.0
2,Accomack,33115.0,269.0,1045.0,8386.0,1450.0,2612.0,1367.0,279.0,182.0
3,Ada,366618.0,1771.0,10165.0,40385.0,21697.0,60359.0,21031.0,6060.0,3509.0
4,Adair,72517.0,348.0,2865.0,14538.0,2885.0,5154.0,2410.0,464.0,653.0
5,Adams,822409.0,8464.0,29043.0,146797.0,44805.0,72993.0,28754.0,4980.0,3002.0
6,Addison,36358.0,106.0,846.0,6991.0,1908.0,5117.0,2617.0,520.0,621.0
7,Aiken,165345.0,1093.0,5902.0,29103.0,8794.0,18337.0,7906.0,1586.0,1439.0
8,Aitkin,16055.0,48.0,603.0,4257.0,1382.0,1370.0,439.0,124.0,45.0
9,Alachua,266511.0,1455.0,6172.0,29535.0,16953.0,33513.0,16720.0,6584.0,7744.0
10,Alamance,162092.0,1458.0,6557.0,24896.0,10470.0,16114.0,5328.0,1021.0,1071.0
11,Alameda,1590894.0,25752.0,17410.0,184655.0,73584.0,274193.0,135848.0,31420.0,31421.0
12,Alamosa,16287.0,194.0,492.0,1927.0,533.0,1309.0,735.0,124.0,171.0
13,Albany,325691.0,1828.0,7248.0,46798.0,22866.0,43380.0,27217.0,6421.0,5457.0
14,Albemarle,81608.0,683.0,1522.0,11022.0,3661.0,13492.0,8451.0,2804.0,2662.0
15,Alcona,10139.0,109.0,401.0,2797.0,691.0,728.0,250.0,74.0,67.0
16,Alcorn,36184.0,345.0,1976.0,6881.0,2250.0,2557.0,988.0,353.0,154.0
17,Aleutians East,3304.0,10.0,79.0,914.0,155.0,306.0,39.0,0.0,9.0
18,Aleutians West (CA),5473.0,17.0,152.0,1241.0,184.0,380.0,138.0,6.0,16.0
19,Alexander,44965.0,634.0,2552.0,9563.0,2632.0,2312.0,792.0,157.0,174.0
20,Alfalfa,5924.0,32.0,437.0,1367.0,224.0,682.0,199.0,9.0,16.0
21,Alger,9323.0,57.0,680.0,2476.0,528.0,969.0,318.0,18.0,46.0
22,Allamakee,14235.0,30.0,397.0,3800.0,968.0,1177.0,309.0,102.0,41.0
23,Allegan,98980.0,610.0,3125.0,22896.0,5560.0,9204.0,3189.0,473.0,385.0
24,Allegany,122917.0,677.0,5083.0,28712.0,8632.0,7858.0,5692.0,771.0,901.0
25,Alleghany,17686.0,103.0,728.0,3743.0,1296.0,1436.0,525.0,126.0,74.0
26,Allegheny,1219265.0,6798.0,30619.0,229223.0,81243.0,190964.0,93184.0,24520.0,18371.0
27,Allen,515908.0,3337.0,15635.0,94066.0,31940.0,49713.0,21015.0,5177.0,2412.0
28,Allendale,9929.0,52.0,439.0,2309.0,477.0,689.0,151.0,0.0,24.0
29,Alpena,29221.0,178.0,918.0,6241.0,2827.0,2178.0,1068.0,284.0,103.0
...,...,...,...,...,...,...,...,...,...,...
1820,Worcester,864547.0,6872.0,20526.0,150475.0,52109.0,124139.0,56978.0,10688.0,9117.0
1821,Worth,26363.0,172.0,1011.0,6253.0,1581.0,1602.0,560.0,72.0,47.0
1822,Wrangell-Petersburg (C,6245.0,18.0,153.0,1359.0,342.0,701.0,221.0,23.0,12.0
1823,Wright,160430.0,712.0,3678.0,29279.0,12264.0,18953.0,5074.0,1065.0,636.0
1824,Wyandot,23911.0,156.0,719.0,7133.0,1652.0,1650.0,599.0,97.0,33.0
1825,Wyandotte,164367.0,2406.0,5253.0,28637.0,7497.0,11388.0,4213.0,745.0,528.0
1826,Wyoming,95991.0,319.0,4159.0,26266.0,6207.0,6228.0,3014.0,380.0,173.0
1827,Wythe,31215.0,277.0,1249.0,7076.0,2131.0,2173.0,1078.0,135.0,174.0
1828,Yadkin,38917.0,420.0,1307.0,8167.0,2853.0,2293.0,830.0,91.0,65.0
1829,Yakima,248684.0,5224.0,9136.0,32196.0,11710.0,14604.0,6138.0,1914.0,729.0
1830,Yalobusha,15618.0,121.0,737.0,3320.0,811.0,689.0,511.0,26.0,105.0
1831,Yamhill,100921.0,974.0,3618.0,16585.0,5166.0,9581.0,3850.0,879.0,613.0
1832,Yancey,17765.0,176.0,859.0,3545.0,1236.0,1719.0,463.0,169.0,131.0
1833,Yankton,21997.0,61.0,1070.0,4272.0,1267.0,3056.0,716.0,255.0,195.0
1834,Yates,26837.0,161.0,961.0,5136.0,1874.0,2152.0,1622.0,309.0,160.0
1835,Yavapai,201147.0,846.0,6613.0,32914.0,13497.0,22301.0,9841.0,2022.0,1464.0
1836,Yazoo,27878.0,572.0,1706.0,4977.0,1081.0,1677.0,675.0,63.0,45.0
1837,Yell,22582.0,389.0,1082.0,5068.0,524.0,1395.0,384.0,65.0,36.0
1838,Yellow Medicine,10734.0,89.0,363.0,2570.0,988.0,880.0,190.0,92.0,19.0
1839,Yellowstone,153904.0,534.0,5204.0,27381.0,7726.0,20953.0,5747.0,1974.0,1007.0
1840,Yoakum,8835.0,48.0,266.0,1243.0,407.0,573.0,151.0,38.0,6.0
1841,Yolo,209126.0,2642.0,3082.0,21037.0,8301.0,24019.0,12505.0,4454.0,6483.0
1842,York,940976.0,4727.0,30027.0,193365.0,58979.0,114868.0,46052.0,8763.0,6021.0
1843,Young,19028.0,133.0,1356.0,3315.0,594.0,1524.0,628.0,121.0,36.0
1844,Yuba,72603.0,1119.0,1844.0,9035.0,4568.0,4292.0,1488.0,410.0,147.0
1845,Yukon-Koyukuk (CA),5600.0,15.0,274.0,1138.0,162.0,261.0,125.0,5.0,5.0
1846,Yuma,213136.0,3036.0,6954.0,26602.0,9643.0,12735.0,5114.0,1156.0,463.0
1847,Zapata,14085.0,133.0,292.0,1715.0,367.0,418.0,223.0,19.0,0.0
1848,Zavala,12077.0,380.0,564.0,1297.0,532.0,481.0,111.0,10.0,15.0
1849,Ziebach,1397.0,11.0,74.0,222.0,62.0,96.0,19.0,1.0,11.0

In [11]:
edu_2015_df.to_csv("Census_2015/edu_2015_by_County.csv")

In [12]:
education_data_2016= "Census_2016/census_education_2016.csv"
census_edu_2016= pd.read_csv(education_data_2016)
census_edu_2016.dtypes

Zipcode                  int64
Population             float64
None                   float64
High School Degree     float64
GED                    float64
Associate Degree       float64
Bachelor Degree        float64
Masters Degree         float64
Professional Degree    float64
Doctorate Degree       float64
dtype: object

In [13]:
census_edu_2016.count()

Zipcode                33120
Population             33120
None                   33120
High School Degree     33120
GED                    33120
Associate Degree       33120
Bachelor Degree        33120
Masters Degree         33120
Professional Degree    33120
Doctorate Degree       33120
dtype: int64

In [14]:
combined_edu_2016=pd.merge(us_data, census_edu_2016, on="Zipcode")
combined_edu_2016.head()
combined_edu_2016.to_csv("Census_2016/combined_edu_2016.csv")

In [15]:
combined_edu_2016.count()

Zipcode                32972
Place Name             32972
State                  32972
State Abbreviation     32972
County                 32972
Latitude               32972
Longitude              32972
Population             32972
None                   32972
High School Degree     32972
GED                    32972
Associate Degree       32972
Bachelor Degree        32972
Masters Degree         32972
Professional Degree    32972
Doctorate Degree       32972
dtype: int64

In [16]:
grouped_edu_2016= combined_edu_2016.groupby(["County"])
grouped_edu_2016.count()

,Zipcode,Place Name,State,State Abbreviation,Latitude,Longitude,Population,None,High School Degree,GED,Associate Degree,Bachelor Degree,Masters Degree,Professional Degree,Doctorate Degree
County,,,,,,,,,,,,,,,
Abbeville,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Acadia,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Accomack,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33
Ada,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Adair,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19
Adams,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88
Addison,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Aiken,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Aitkin,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Alachua,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20
Alamance,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Alameda,49,49,49,49,49,49,49,49,49,49,49,49,49,49,49
Alamosa,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Albany,46,46,46,46,46,46,46,46,46,46,46,46,46,46,46
Albemarle,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Alcona,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Alcorn,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Aleutians East,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Aleutians West (CA),7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Alexander,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Alfalfa,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Alger,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Allamakee,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Allegan,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14
Allegany,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40
Alleghany,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Allegheny,101,101,101,101,101,101,101,101,101,101,101,101,101,101,101
Allen,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56
Allendale,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Alpena,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Worcester,97,97,97,97,97,97,97,97,97,97,97,97,97,97,97
Worth,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Wrangell-Petersburg (C,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
Wright,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30
Wyandot,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
Wyandotte,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12
Wyoming,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61
Wythe,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9
Yadkin,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Yakima,21,21,21,21,21,21,21,21,21,21,21,21,21,21,21
Yalobusha,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Yamhill,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yancey,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Yankton,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Yates,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yavapai,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26
Yazoo,6,6,6,6,6,6,6,6,6,6,6,6,6,6,6
Yell,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
Yellow Medicine,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
Yellowstone,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13
Yoakum,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Yolo,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18
York,99,99,99,99,99,99,99,99,99,99,99,99,99,99,99
Young,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Yuba,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11
Yukon-Koyukuk (CA),29,29,29,29,29,29,29,29,29,29,29,29,29,29,29
Yuma,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
Zapata,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Zavala,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
Ziebach,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2

In [17]:
population_sum=grouped_edu_2016["Population"].sum().tolist()
none_sum=grouped_edu_2016["None"].sum().tolist()
ged_sum=grouped_edu_2016["GED"].sum().tolist()
high_school_sum=grouped_edu_2016["High School Degree"].sum().tolist()
associate_sum=grouped_edu_2016["Associate Degree"].sum().tolist()
bachelor_sum=grouped_edu_2016["Bachelor Degree"].sum().tolist()
masters_sum=grouped_edu_2016["Masters Degree"].sum().tolist()
doctorate_sum=grouped_edu_2016["Doctorate Degree"].sum().tolist()
professional_sum=grouped_edu_2016["Professional Degree"].sum().tolist()

In [18]:
county_edu_list_2016=[]
for x, group in grouped_edu_2016:
    county_edu_list_2016.append(x)
    
print(len(county_edu_list_2016))

1850

In [19]:
edu_2016_df=pd.DataFrame(county_edu_list_2016, columns=["County"])
edu_2016_df["Population"]= population_sum
edu_2016_df["None"]= none_sum
edu_2016_df["GED"]= ged_sum
edu_2016_df["High School Degree"]= high_school_sum
edu_2016_df["Associate Degree"]= associate_sum
edu_2016_df["Bachelor Degree"]= bachelor_sum
edu_2016_df["Masters Degree"]= masters_sum
edu_2016_df["Professional Degree"]= professional_sum
edu_2016_df["Doctorate Degree"]= doctorate_sum

edu_2016_df

,County,Population,None,GED,High School Degree,Associate Degree,Bachelor Degree,Masters Degree,Professional Degree,Doctorate Degree
0,Abbeville,20747.0,167.0,900.0,4035.0,1388.0,1244.0,428.0,85.0,75.0
1,Acadia,61112.0,714.0,2156.0,13419.0,2384.0,3226.0,852.0,242.0,103.0
2,Accomack,33060.0,279.0,1067.0,8590.0,1429.0,2647.0,1230.0,225.0,271.0
3,Ada,373433.0,1640.0,10913.0,42097.0,23155.0,61864.0,21297.0,6215.0,3784.0
4,Adair,72700.0,303.0,2824.0,14657.0,3048.0,5203.0,2543.0,434.0,704.0
5,Adams,831891.0,8565.0,28914.0,148304.0,45623.0,75027.0,29619.0,5028.0,3265.0
6,Addison,36344.0,123.0,836.0,6982.0,2002.0,5206.0,2612.0,573.0,570.0
7,Aiken,166495.0,1221.0,6395.0,28986.0,9061.0,18538.0,8411.0,1483.0,1413.0
8,Aitkin,15914.0,42.0,640.0,4093.0,1419.0,1421.0,447.0,144.0,25.0
9,Alachua,268516.0,1650.0,6468.0,30600.0,16791.0,33677.0,17233.0,6788.0,7726.0
10,Alamance,163481.0,1309.0,7074.0,24567.0,11126.0,16743.0,5589.0,1203.0,1083.0
11,Alameda,1611207.0,26835.0,18212.0,182438.0,74505.0,284328.0,142861.0,33162.0,32020.0
12,Alamosa,16398.0,215.0,439.0,1865.0,475.0,1404.0,747.0,89.0,160.0
13,Albany,326664.0,1817.0,7061.0,45534.0,23155.0,44331.0,27788.0,6495.0,5893.0
14,Albemarle,82037.0,722.0,1561.0,10399.0,3482.0,13945.0,8560.0,2796.0,2806.0
15,Alcona,10061.0,124.0,449.0,2769.0,712.0,744.0,251.0,70.0,60.0
16,Alcorn,36420.0,320.0,1753.0,6772.0,2230.0,2550.0,1021.0,426.0,161.0
17,Aleutians East,3299.0,4.0,79.0,991.0,179.0,250.0,43.0,0.0,11.0
18,Aleutians West (CA),5512.0,11.0,170.0,1450.0,245.0,455.0,134.0,10.0,16.0
19,Alexander,44113.0,520.0,2848.0,9260.0,2838.0,2308.0,948.0,150.0,89.0
20,Alfalfa,5993.0,25.0,460.0,1324.0,244.0,697.0,216.0,10.0,23.0
21,Alger,9149.0,63.0,749.0,2444.0,546.0,926.0,316.0,19.0,54.0
22,Allamakee,14218.0,29.0,374.0,3631.0,1073.0,1207.0,314.0,99.0,49.0
23,Allegan,100018.0,631.0,3182.0,22766.0,5927.0,9293.0,3491.0,531.0,426.0
24,Allegany,121890.0,659.0,5112.0,28149.0,8801.0,8007.0,5807.0,794.0,988.0
25,Alleghany,17499.0,104.0,622.0,3758.0,1347.0,1456.0,637.0,137.0,80.0
26,Allegheny,1218281.0,6737.0,30645.0,222003.0,82741.0,198926.0,96188.0,25122.0,19061.0
27,Allen,518817.0,3408.0,16273.0,92602.0,33114.0,51133.0,21282.0,5267.0,2263.0
28,Allendale,9614.0,78.0,393.0,2326.0,495.0,526.0,102.0,0.0,23.0
29,Alpena,29065.0,176.0,928.0,6235.0,2732.0,2198.0,1128.0,269.0,91.0
...,...,...,...,...,...,...,...,...,...,...
1820,Worcester,867019.0,6788.0,20405.0,152150.0,51785.0,125168.0,59355.0,10747.0,9334.0
1821,Worth,26556.0,175.0,1158.0,6097.0,1750.0,1612.0,604.0,77.0,67.0
1822,Wrangell-Petersburg (C,6267.0,36.0,162.0,1345.0,339.0,668.0,247.0,20.0,7.0
1823,Wright,161036.0,650.0,3984.0,29560.0,13162.0,18654.0,4992.0,1114.0,783.0
1824,Wyandot,24066.0,197.0,740.0,7171.0,1699.0,1716.0,575.0,123.0,31.0
1825,Wyandotte,165428.0,2515.0,5446.0,28604.0,7528.0,11812.0,4363.0,860.0,564.0
1826,Wyoming,94971.0,304.0,4110.0,26337.0,6367.0,6162.0,3012.0,418.0,199.0
1827,Wythe,30900.0,263.0,1237.0,7253.0,2184.0,2309.0,928.0,235.0,125.0
1828,Yadkin,38985.0,378.0,1501.0,8020.0,2693.0,2341.0,870.0,107.0,79.0
1829,Yakima,249145.0,4887.0,9551.0,32739.0,11976.0,14046.0,5954.0,1940.0,838.0
1830,Yalobusha,16095.0,83.0,864.0,3175.0,824.0,906.0,451.0,50.0,80.0
1831,Yamhill,102390.0,691.0,3425.0,15810.0,5658.0,10511.0,4078.0,872.0,727.0
1832,Yancey,17770.0,276.0,874.0,3684.0,1250.0,1745.0,505.0,159.0,158.0
1833,Yankton,21947.0,56.0,1060.0,3966.0,1463.0,2941.0,890.0,256.0,213.0
1834,Yates,26983.0,113.0,1076.0,5010.0,1931.0,2278.0,1464.0,169.0,160.0
1835,Yavapai,203845.0,729.0,7032.0,33532.0,14459.0,22388.0,10551.0,2012.0,1650.0
1836,Yazoo,27691.0,578.0,2210.0,4941.0,1031.0,1489.0,678.0,89.0,130.0
1837,Yell,22496.0,369.0,1108.0,5104.0,539.0,1512.0,486.0,105.0,36.0
1838,Yellow Medicine,10702.0,86.0,334.0,2577.0,964.0,918.0,174.0,72.0,18.0
1839,Yellowstone,155540.0,536.0,5113.0,27805.0,8364.0,21581.0,6447.0,1894.0,963.0
1840,Yoakum,9061.0,98.0,228.0,1273.0,396.0,673.0,205.0,37.0,12.0
1841,Yolo,211422.0,2851.0,3297.0,20568.0,8175.0,25255.0,12877.0,4591.0,6611.0
1842,York,947713.0,5103.0,30249.0,193736.0,60404.0,116298.0,47596.0,8548.0,6458.0
1843,Young,19096.0,131.0,1265.0,3160.0,517.0,1629.0,670.0,132.0,27.0
1844,Yuba,73015.0,938.0,1724.0,8979.0,4807.0,4716.0,1702.0,438.0,116.0
1845,Yukon-Koyukuk (CA),5536.0,19.0,275.0,1123.0,153.0,280.0,147.0,3.0,10.0
1846,Yuma,213411.0,3462.0,6707.0,27806.0,9407.0,12881.0,5218.0,1027.0,454.0
1847,Zapata,13956.0,159.0,285.0,1458.0,343.0,417.0,214.0,23.0,0.0
1848,Zavala,12149.0,351.0,518.0,1435.0,544.0,459.0,140.0,17.0,16.0
1849,Ziebach,1409.0,17.0,68.0,232.0,68.0,113.0,25.0,2.0,0.0

In [20]:
edu_2016_df.to_csv("Census_2016/edu_2016_by_County.csv")